apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: build-me
  name: build-me
spec:
  selector:
    matchLabels:
      app: build-me
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: build-me
    spec:
      containers:
      - name: build-me
        image: docker.io/opsmx11/build-me:9c5d6d6-10
