apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-swarm-visualizer
  name: docker-swarm-visualizer
spec:
  selector:
    matchLabels:
      app: docker-swarm-visualizer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: docker-swarm-visualizer
    spec:
      containers:
      - name: docker-swarm-visualizer
        image: docker.io/opsmx11/docker-swarm:9839424-57
